// <auto-generated />
using System;
using System.Collections.Generic;
using GameBug.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;

#nullable disable

namespace GameBug.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(GameBugDbContext))]
    [Migration("20260711150424_Phase34ReliabilityHardening")]
    partial class Phase34ReliabilityHardening
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GameBug.Domain.Analysis.AnalysisAiExecution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AnalysisRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("analysis_run_id");

                    b.Property<int>("Attempt")
                        .HasColumnType("integer")
                        .HasColumnName("attempt");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("InputTokens")
                        .HasColumnType("integer")
                        .HasColumnName("input_tokens");

                    b.Property<bool>("IsSelected")
                        .HasColumnType("boolean")
                        .HasColumnName("is_selected");

                    b.Property<long?>("LatencyMs")
                        .HasColumnType("bigint")
                        .HasColumnName("latency_ms");

                    b.Property<string>("OutputHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("output_hash");

                    b.Property<int?>("OutputTokens")
                        .HasColumnType("integer")
                        .HasColumnName("output_tokens");

                    b.Property<string>("PromptVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("prompt_version");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("provider");

                    b.Property<string>("ProviderRequestIdHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("provider_request_id_hash");

                    b.Property<string>("RequestedModel")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("requested_model");

                    b.Property<string>("ResolvedModel")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("resolved_model");

                    b.Property<string>("RouteProfile")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("route_profile");

                    b.Property<string>("RoutingPolicyVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("routing_policy_version");

                    b.Property<string>("RoutingReason")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("routing_reason");

                    b.Property<string>("SafeErrorCode")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("safe_error_code");

                    b.Property<string>("SchemaVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("schema_version");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.Property<string>("Task")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("task");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisRunId");

                    b.ToTable("analysis_ai_executions", (string)null);
                });

            modelBuilder.Entity("GameBug.Domain.Analysis.AnalysisAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AnalysisRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("analysis_run_id");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_number");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<long?>("DurationMs")
                        .HasColumnType("bigint")
                        .HasColumnName("duration_ms");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("error_code");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("outcome");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("WorkerId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("worker_id");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisRunId", "AttemptNumber");

                    b.ToTable("analysis_attempts", (string)null);
                });

            modelBuilder.Entity("GameBug.Domain.Analysis.AnalysisCheckpoint", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AnalysisRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("analysis_run_id");

                    b.Property<int>("Attempt")
                        .HasColumnType("integer")
                        .HasColumnName("attempt");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("error_code");

                    b.Property<string>("InputHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("input_hash");

                    b.Property<string>("OutputReference")
                        .HasColumnType("jsonb")
                        .HasColumnName("output_reference");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("stage");

                    b.Property<string>("StageVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("stage_version");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<string>("WarningCodesJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("warning_codes");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisRunId", "Stage", "StageVersion", "InputHash")
                        .IsUnique()
                        .HasFilter("status = 'Completed'");

                    b.ToTable("analysis_checkpoints", (string)null);
                });

            modelBuilder.Entity("GameBug.Domain.Analysis.AnalysisExecutionLease", b =>
                {
                    b.Property<Guid>("AnalysisRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("analysis_run_id");

                    b.Property<string>("LockedBy")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("locked_by");

                    b.Property<DateTimeOffset>("LockedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("locked_until");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("AnalysisRunId");

                    b.ToTable("analysis_execution_locks", (string)null);
                });

            modelBuilder.Entity("GameBug.Domain.Analysis.AnalysisJob", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AnalysisRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("analysis_run_id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<DateTimeOffset>("AvailableAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("available_at");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("ExpectedVersion")
                        .HasColumnType("integer")
                        .HasColumnName("expected_version");

                    b.Property<string>("LastErrorCode")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("last_error_code");

                    b.Property<string>("LockedBy")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("locked_by");

                    b.Property<DateTimeOffset?>("LockedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("locked_until");

                    b.Property<string>("QueueName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("queue_name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("QueueName", "AnalysisRunId", "ExpectedVersion")
                        .IsUnique();

                    b.HasIndex("QueueName", "Status", "AvailableAt");

                    b.ToTable("analysis_jobs", null, t =>
                        {
                            t.HasCheckConstraint("CK_analysis_jobs_attempt", "attempt_count >= 0");
                        });
                });

            modelBuilder.Entity("GameBug.Domain.Analysis.AnalysisOutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AggregateId")
                        .HasColumnType("uuid")
                        .HasColumnName("aggregate_id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<string>("DispatchStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("dispatch_status");

                    b.Property<DateTimeOffset?>("DispatchedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dispatched_at");

                    b.Property<string>("LastErrorCode")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("last_error_code");

                    b.Property<string>("LockedBy")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("locked_by");

                    b.Property<DateTimeOffset?>("LockedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("locked_until");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("message_type");

                    b.Property<DateTimeOffset>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload_json");

                    b.HasKey("Id");

                    b.HasIndex("AggregateId");

                    b.HasIndex("DispatchStatus", "NextAttemptAt");

                    b.ToTable("analysis_outbox", null, t =>
                        {
                            t.HasCheckConstraint("CK_analysis_outbox_attempt", "attempt_count >= 0");
                        });
                });

            modelBuilder.Entity("GameBug.Domain.Analysis.AnalysisRun", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CancellationRequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancellation_requested_at");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("ConfigurationHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("configuration_hash");

                    b.Property<int>("CurrentAttempt")
                        .HasColumnType("integer")
                        .HasColumnName("current_attempt");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("error_code");

                    b.Property<string>("FailureCategory")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("failure_category");

                    b.Property<string>("InputHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("input_hash");

                    b.Property<DateTimeOffset?>("LastHeartbeatAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_heartbeat_at");

                    b.Property<DateTimeOffset?>("NextRetryAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_retry_at");

                    b.Property<string>("ParserVersion")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("parser_version");

                    b.Property<int>("ProgressPercent")
                        .HasColumnType("integer")
                        .HasColumnName("progress_percent");

                    b.Property<DateTimeOffset?>("QueuedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("queued_at");

                    b.Property<Guid>("ReportId")
                        .HasColumnType("uuid")
                        .HasColumnName("report_id");

                    b.Property<string>("ResultReference")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("result_reference");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("retry_count");

                    b.Property<string>("RoutingPolicyVersion")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("routing_policy_version");

                    b.Property<string>("SanitizerVersion")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("sanitizer_version");

                    b.Property<string>("SchemaVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("schema_version");

                    b.Property<Guid?>("SelectedReproExecutionId")
                        .HasColumnType("uuid")
                        .HasColumnName("selected_repro_execution_id");

                    b.Property<string>("Stage")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("stage");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.Property<long>("VersionToken")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version_token");

                    b.Property<string>("Warnings")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("warnings_json");

                    b.HasKey("Id");

                    b.HasIndex("SelectedReproExecutionId");

                    b.HasIndex("ReportId", "Version")
                        .IsUnique();

                    b.HasIndex("Status", "StartedAt");

                    b.HasIndex("ReportId", "InputHash", "ConfigurationHash")
                        .IsUnique()
                        .HasFilter("status IN ('Received', 'Queued', 'Processing')");

                    b.ToTable("analysis_runs", null, t =>
                        {
                            t.HasCheckConstraint("CK_analysis_runs_progress", "progress_percent >= 0 AND progress_percent <= 100");

                            t.HasCheckConstraint("CK_analysis_runs_retry_count", "retry_count >= 0");

                            t.HasCheckConstraint("CK_analysis_runs_version", "version > 0");
                        });
                });

            modelBuilder.Entity("GameBug.Domain.BugReports.Attachment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AttachmentType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("attachment_type");

                    b.Property<Guid>("BugReportId")
                        .HasColumnType("uuid")
                        .HasColumnName("report_id");

                    b.Property<string>("Checksum")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("checksum");

                    b.Property<string>("ChecksumAlgorithm")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("checksum_algorithm");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("original_file_name");

                    b.Property<string>("ScanStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("scan_status");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("storage_key");

                    b.HasKey("Id");

                    b.HasIndex("BugReportId");

                    b.HasIndex("StorageKey")
                        .IsUnique();

                    b.ToTable("attachments", (string)null);
                });

            modelBuilder.Entity("GameBug.Domain.BugReports.BugReport", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BuildVersion")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("build_version");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("raw_text");

                    b.Property<string>("Device")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("device");

                    b.Property<string>("Locale")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("locale");

                    b.Property<string>("Platform")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("platform");

                    b.Property<string>("SessionReference")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("session_reference");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("Status", "CreatedAt");

                    b.ToTable("bug_reports", (string)null);
                });

            modelBuilder.Entity("GameBug.Domain.Duplicates.DuplicateMatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AnalysisRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("analysis_run_id");

                    b.Property<string>("CandidateSnapshotHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("candidate_snapshot_hash");

                    b.Property<string>("ChannelScoresJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("channel_scores_json");

                    b.Property<string>("Classification")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("classification");

                    b.Property<string>("ConflictingSignalsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("conflicting_signals_json");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Explanation")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("explanation");

                    b.Property<double>("FinalScore")
                        .HasColumnType("double precision")
                        .HasColumnName("final_score");

                    b.Property<Guid>("HistoricalTicketId")
                        .HasColumnType("uuid")
                        .HasColumnName("historical_ticket_id");

                    b.Property<string>("MatchingSignalsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("matching_signals_json");

                    b.Property<int>("Rank")
                        .HasColumnType("integer")
                        .HasColumnName("rank");

                    b.Property<string>("RankerVersion")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("ranker_version");

                    b.Property<string>("RerankerModel")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("reranker_model");

                    b.Property<string>("RerankerVersion")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("reranker_version");

                    b.Property<string>("SignalScoresJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("signal_scores_json");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisRunId", "HistoricalTicketId")
                        .IsUnique();

                    b.HasIndex("AnalysisRunId", "Rank")
                        .IsUnique();

                    b.ToTable("duplicate_matches", null, t =>
                        {
                            t.HasCheckConstraint("CK_duplicate_matches_rank", "rank > 0");

                            t.HasCheckConstraint("CK_duplicate_matches_score", "final_score >= 0 AND final_score <= 1");
                        });
                });

            modelBuilder.Entity("GameBug.Domain.Duplicates.EmbeddingCacheEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("content_hash");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Dimension")
                        .HasColumnType("integer")
                        .HasColumnName("dimension");

                    b.Property<string>("EmbeddingVersion")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("embedding_version");

                    b.Property<DateTimeOffset>("LastUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("model");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("provider");

                    b.Property<Vector>("Vector")
                        .IsRequired()
                        .HasColumnType("vector")
                        .HasColumnName("vector");

                    b.HasKey("Id");

                    b.HasIndex("ContentHash", "Provider", "Model", "EmbeddingVersion", "Dimension")
                        .IsUnique();

                    b.ToTable("embedding_cache", (string)null);
                });

            modelBuilder.Entity("GameBug.Domain.Duplicates.HistoricalTicket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActualResult")
                        .HasColumnType("text")
                        .HasColumnName("actual_result");

                    b.Property<string>("BuildMax")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("build_max");

                    b.Property<string>("BuildMin")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("build_min");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector")
                        .HasColumnName("embedding");

                    b.Property<int?>("EmbeddingDimension")
                        .HasColumnType("integer")
                        .HasColumnName("embedding_dimension");

                    b.Property<string>("EmbeddingModel")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("embedding_model");

                    b.Property<string>("EmbeddingProvider")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("embedding_provider");

                    b.Property<string>("EmbeddingVersion")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("embedding_version");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("external_id");

                    b.PrimitiveCollection<string[]>("GameEntities")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("game_entities");

                    b.Property<string>("ImportVersion")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("import_version");

                    b.Property<DateTimeOffset?>("IndexedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("indexed_at");

                    b.PrimitiveCollection<string[]>("Platforms")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("platforms");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("SceneOrFeature")
                        .HasColumnType("text")
                        .HasColumnName("scene_or_feature");

                    b.Property<string>("SearchText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("search_text");

                    b.Property<string>("SearchTextHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("search_text_hash");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("severity");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("source");

                    b.Property<DateTimeOffset>("SourceUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("source_updated_at");

                    b.Property<string>("StackSignature")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("stack_signature");

                    b.Property<string>("StackSummary")
                        .HasColumnType("text")
                        .HasColumnName("stack_summary");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.Property<string>("SummarySanitized")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("summary_sanitized");

                    b.Property<string>("Symptom")
                        .HasColumnType("text")
                        .HasColumnName("symptom");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<string>("TriggerAction")
                        .HasColumnType("text")
                        .HasColumnName("trigger_action");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("StackSignature");

                    b.HasIndex("ProjectId", "Status");

                    b.HasIndex("EmbeddingVersion", "EmbeddingDimension", "IndexedAt");

                    b.HasIndex("ProjectId", "Source", "ExternalId")
                        .IsUnique();

                    b.ToTable("historical_tickets", (string)null);
                });

            modelBuilder.Entity("GameBug.Domain.Duplicates.TicketImportBatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AcceptedCount")
                        .HasColumnType("integer")
                        .HasColumnName("accepted_count");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("actor");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ErrorsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("errors_json");

                    b.Property<string>("FileHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("file_hash");

                    b.Property<string>("ImportVersion")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("import_version");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<int>("RejectedCount")
                        .HasColumnType("integer")
                        .HasColumnName("rejected_count");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("source");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "Source", "FileHash", "ImportVersion")
                        .IsUnique();

                    b.ToTable("ticket_import_batches", (string)null);
                });

            modelBuilder.Entity("GameBug.Domain.Evidence.EventTimelineEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AnalysisRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("analysis_run_id");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("event_name");

                    b.Property<string>("Excerpt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("excerpt");

                    b.Property<string>("ExcerptHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("excerpt_hash");

                    b.Property<int>("RelativeSequence")
                        .HasColumnType("integer")
                        .HasColumnName("relative_sequence");

                    b.Property<int?>("SourceLine")
                        .HasColumnType("integer")
                        .HasColumnName("source_line");

                    b.Property<string>("SourceRef")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("source_ref");

                    b.Property<DateTimeOffset?>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisRunId");

                    b.ToTable("event_timeline", (string)null);
                });

            modelBuilder.Entity("GameBug.Domain.Evidence.EvidenceFact", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AnalysisRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("analysis_run_id");

                    b.Property<double>("Confidence")
                        .HasColumnType("double precision")
                        .HasColumnName("confidence");

                    b.Property<string>("FactType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("fact_type");

                    b.Property<string>("NormalizedValue")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("normalized_value");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisRunId");

                    b.ToTable("evidence_facts", null, t =>
                        {
                            t.HasCheckConstraint("CK_evidence_facts_confidence", "confidence >= 0 AND confidence <= 1");
                        });
                });

            modelBuilder.Entity("GameBug.Domain.Evidence.EvidenceSource", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("EvidenceFactId")
                        .HasColumnType("uuid")
                        .HasColumnName("evidence_fact_id");

                    b.Property<string>("ExcerptHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("excerpt_hash");

                    b.Property<int?>("LineEnd")
                        .HasColumnType("integer")
                        .HasColumnName("line_end");

                    b.Property<int?>("LineStart")
                        .HasColumnType("integer")
                        .HasColumnName("line_start");

                    b.Property<string>("SanitizedExcerpt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sanitized_excerpt");

                    b.Property<string>("SourceRef")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("source_ref");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("source_type");

                    b.Property<string>("TrustLevel")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("trust_level");

                    b.HasKey("Id");

                    b.HasIndex("EvidenceFactId");

                    b.ToTable("evidence_sources", (string)null);
                });

            modelBuilder.Entity("GameBug.Domain.GameContext.ExpectedBehavior", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BuildRangeEnd")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("build_range_end");

                    b.Property<string>("BuildRangeStart")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("build_range_start");

                    b.Property<string>("ExpectedOutcome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("expected_outcome");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<string>("Trigger")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("trigger");

                    b.HasKey("Id");

                    b.ToTable("expected_behaviors", (string)null);
                });

            modelBuilder.Entity("GameBug.Domain.GameContext.GameEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.PrimitiveCollection<string[]>("Aliases")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("aliases");

                    b.Property<string>("BuildRangeEnd")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("build_range_end");

                    b.Property<string>("BuildRangeStart")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("build_range_start");

                    b.Property<string>("CanonicalName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("canonical_name");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("CanonicalName")
                        .IsUnique();

                    b.ToTable("game_entities", (string)null);
                });

            modelBuilder.Entity("GameBug.Domain.ReproCases.ReproCase", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActualResult")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("actual_result");

                    b.Property<Guid>("AnalysisRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("analysis_run_id");

                    b.Property<string>("BuildVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("build_version");

                    b.Property<string>("ExpectedResult")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("expected_result");

                    b.Property<string>("MissingInformation")
                        .HasColumnType("text")
                        .HasColumnName("missing_information");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("platform");

                    b.Property<string>("Preconditions")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("preconditions");

                    b.Property<string>("SeverityEstimate")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("severity_estimate");

                    b.Property<string>("SeverityReason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("severity_reason");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("title");

                    b.ComplexProperty<Dictionary<string, object>>("Confidence", "GameBug.Domain.ReproCases.ReproCase.Confidence#ConfidenceScore", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<double>("Value")
                                .HasColumnType("double precision")
                                .HasColumnName("confidence");
                        });

                    b.HasKey("Id");

                    b.HasIndex("AnalysisRunId")
                        .IsUnique();

                    b.ToTable("repro_cases", null, t =>
                        {
                            t.HasCheckConstraint("CK_repro_cases_confidence", "confidence >= 0 AND confidence <= 1");
                        });
                });

            modelBuilder.Entity("GameBug.Domain.ReproCases.ReproStep", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("InferenceReason")
                        .HasColumnType("text")
                        .HasColumnName("inference_reason");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("step_order");

                    b.Property<Guid>("ReproCaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("repro_case_id");

                    b.Property<Guid?>("SourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_id");

                    b.Property<string>("StepType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("step_type");

                    b.HasKey("Id");

                    b.HasIndex("ReproCaseId", "Order")
                        .IsUnique();

                    b.ToTable("repro_steps", (string)null);
                });

            modelBuilder.Entity("GameBug.Infrastructure.HistoricalTickets.HistoricalTicketIndexJobEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<DateTimeOffset>("AvailableAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("available_at");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("LastErrorCode")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("last_error_code");

                    b.Property<string>("LockedBy")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("locked_by");

                    b.Property<DateTimeOffset?>("LockedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("locked_until");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uuid")
                        .HasColumnName("ticket_id");

                    b.HasKey("Id");

                    b.HasIndex("TicketId");

                    b.HasIndex("Status", "AvailableAt");

                    b.ToTable("historical_ticket_index_jobs", null, t =>
                        {
                            t.HasCheckConstraint("CK_historical_ticket_index_jobs_attempt", "attempt_count >= 0");
                        });
                });

            modelBuilder.Entity("GameBug.Infrastructure.Persistence.AuditEventEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("action");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("actor");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("entity_type");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.HasKey("Id");

                    b.HasIndex("EntityType", "EntityId", "CreatedAt");

                    b.ToTable("audit_events", (string)null);
                });

            modelBuilder.Entity("GameBug.Infrastructure.Persistence.IdempotencyRequestEntity", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("key");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiryTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expiry_time");

                    b.Property<Guid?>("ReportId")
                        .HasColumnType("uuid")
                        .HasColumnName("report_id");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("request_hash");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.HasKey("Key");

                    b.ToTable("idempotency_requests", (string)null);
                });

            modelBuilder.Entity("GameBug.Domain.Analysis.AnalysisAiExecution", b =>
                {
                    b.HasOne("GameBug.Domain.Analysis.AnalysisRun", null)
                        .WithMany("AiExecutions")
                        .HasForeignKey("AnalysisRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GameBug.Domain.Analysis.AnalysisRun", b =>
                {
                    b.HasOne("GameBug.Domain.Analysis.AnalysisAiExecution", null)
                        .WithMany()
                        .HasForeignKey("SelectedReproExecutionId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("GameBug.Domain.BugReports.Attachment", b =>
                {
                    b.HasOne("GameBug.Domain.BugReports.BugReport", null)
                        .WithMany("Attachments")
                        .HasForeignKey("BugReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GameBug.Domain.Evidence.EventTimelineEntry", b =>
                {
                    b.HasOne("GameBug.Domain.Analysis.AnalysisRun", null)
                        .WithMany()
                        .HasForeignKey("AnalysisRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GameBug.Domain.Evidence.EvidenceFact", b =>
                {
                    b.HasOne("GameBug.Domain.Analysis.AnalysisRun", null)
                        .WithMany()
                        .HasForeignKey("AnalysisRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GameBug.Domain.Evidence.EvidenceSource", b =>
                {
                    b.HasOne("GameBug.Domain.Evidence.EvidenceFact", null)
                        .WithMany("Sources")
                        .HasForeignKey("EvidenceFactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GameBug.Domain.ReproCases.ReproCase", b =>
                {
                    b.HasOne("GameBug.Domain.Analysis.AnalysisRun", null)
                        .WithOne()
                        .HasForeignKey("GameBug.Domain.ReproCases.ReproCase", "AnalysisRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GameBug.Domain.ReproCases.ReproStep", b =>
                {
                    b.HasOne("GameBug.Domain.ReproCases.ReproCase", null)
                        .WithMany("Steps")
                        .HasForeignKey("ReproCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GameBug.Domain.Analysis.AnalysisRun", b =>
                {
                    b.Navigation("AiExecutions");
                });

            modelBuilder.Entity("GameBug.Domain.BugReports.BugReport", b =>
                {
                    b.Navigation("Attachments");
                });

            modelBuilder.Entity("GameBug.Domain.Evidence.EvidenceFact", b =>
                {
                    b.Navigation("Sources");
                });

            modelBuilder.Entity("GameBug.Domain.ReproCases.ReproCase", b =>
                {
                    b.Navigation("Steps");
                });
#pragma warning restore 612, 618
        }
    }
}
