using GameBug.Application.Abstractions.Persistence;
using GameBug.Application.Abstractions.Security;
using GameBug.Application.Abstractions.Observability;
using GameBug.Application.Abstractions.Time;
using GameBug.Application.QaWorkflow;
using GameBug.Domain.Analysis;
using GameBug.Domain.QaWorkflow;
using GameBug.Domain.SharedKernel;
using MediatR;

namespace GameBug.Application.QaWorkflow.OpenReview;

internal sealed class OpenQaReviewCommandHandler : IRequestHandler<OpenQaReviewCommand, Result<Guid>>
{
    private readonly IQaReviewRepository _reviewRepository;
    private readonly IAnalysisRunRepository _analysisRunRepository;
    private readonly IBugReportRepository _bugReportRepository;
    private readonly IIdempotencyStore _idempotencyStore;
    private readonly IUnitOfWork _unitOfWork;
    private readonly ICurrentUser _currentUser;
    private readonly IClock _clock;
    private readonly IAuditWriter _auditWriter;

    public OpenQaReviewCommandHandler(
        IQaReviewRepository reviewRepository,
        IAnalysisRunRepository analysisRunRepository,
        IBugReportRepository bugReportRepository,
        IIdempotencyStore idempotencyStore,
        IUnitOfWork unitOfWork,
        ICurrentUser currentUser,
        IClock clock,
        IAuditWriter auditWriter)
    {
        _reviewRepository = reviewRepository;
        _analysisRunRepository = analysisRunRepository;
        _bugReportRepository = bugReportRepository;
        _idempotencyStore = idempotencyStore;
        _unitOfWork = unitOfWork;
        _currentUser = currentUser;
        _clock = clock;
        _auditWriter = auditWriter;
    }

    public async Task<Result<Guid>> Handle(OpenQaReviewCommand request, CancellationToken cancellationToken)
    {
        if (!_currentUser.IsAuthenticated || string.IsNullOrWhiteSpace(_currentUser.UserId))
        {
            return Result.Failure<Guid>(new DomainError("Auth.Unauthorized", "User is not authenticated."));
        }

        string requestHash = QaWorkflowIdempotency.Hash(request.AnalysisRunId, request.CandidateSnapshotHash);
        string scopedKey = QaWorkflowIdempotency.Scope(
            _currentUser.UserId,
            "POST",
            $"/api/v1/analyses/{request.AnalysisRunId}/review",
            request.IdempotencyKey);
        var idempotency = await QaWorkflowIdempotency.ReserveAsync(
            _idempotencyStore, _clock, scopedKey, requestHash, cancellationToken);
        if (idempotency.IsFailure)
        {
            return Result.Failure<Guid>(idempotency.Error);
        }

        if (idempotency.Value.IsReplay && idempotency.Value.ReplayId.HasValue)
        {
            return idempotency.Value.ReplayId.Value;
        }

        var analysisId = new AnalysisRunId(request.AnalysisRunId);
        
        var existingReview = await _reviewRepository.GetByAnalysisRunIdAsync(analysisId, cancellationToken);
        if (existingReview != null)
        {
            await QaWorkflowIdempotency.CompleteAsync(
                _idempotencyStore, idempotency.Value, existingReview.Id.Value, _clock, cancellationToken);
            await _unitOfWork.SaveChangesAsync(cancellationToken);
            return existingReview.Id.Value;
        }

        var analysisRun = await _analysisRunRepository.GetAsync(analysisId, cancellationToken);
        if (analysisRun == null)
        {
            await ReleaseReservationAsync(idempotency.Value, cancellationToken);
            return Result.Failure<Guid>(new DomainError("OpenReview.AnalysisNotFound", "Analysis run not found."));
        }

        var bugReport = await _bugReportRepository.GetAsync(new GameBug.Domain.BugReports.BugReportId(analysisRun.ReportId.Value), cancellationToken);
        if (bugReport == null)
        {
            await ReleaseReservationAsync(idempotency.Value, cancellationToken);
            return Result.Failure<Guid>(new DomainError("OpenReview.ReportNotFound", "Bug report not found."));
        }

        // We check the snapshot hash matches the one generated by Phase 4
        var matches = await _analysisRunRepository.GetDuplicateMatchesAsync(analysisId, cancellationToken);
        if (matches.Count == 0)
        {
            await ReleaseReservationAsync(idempotency.Value, cancellationToken);
            return Result.Failure<Guid>(new DomainError("DUPLICATE_GATE_REQUIRED", "QA review requires a persisted duplicate candidate snapshot."));
        }

        var snapshotHash = matches.First().CandidateSnapshotHash;
        
        if (request.CandidateSnapshotHash != snapshotHash)
        {
            await ReleaseReservationAsync(idempotency.Value, cancellationToken);
            return Result.Failure<Guid>(new DomainError("CANDIDATE_SNAPSHOT_MISMATCH", "Provided snapshot hash does not match the actual snapshot hash for this analysis."));
        }

        var reviewResult = QaReview.Open(
            QaReviewId.CreateUnique(),
            analysisRun,
            request.CandidateSnapshotHash,
            _currentUser.UserId!,
            _clock.UtcNow);

        if (reviewResult.IsFailure)
        {
            await ReleaseReservationAsync(idempotency.Value, cancellationToken);
            return Result.Failure<Guid>(reviewResult.Error);
        }

        var review = reviewResult.Value;

        var reportUpdateResult = bugReport.BeginQaReview(_clock.UtcNow);
        if (reportUpdateResult.IsFailure)
        {
            await ReleaseReservationAsync(idempotency.Value, cancellationToken);
            return Result.Failure<Guid>(reportUpdateResult.Error);
        }

        await _unitOfWork.BeginTransactionAsync(cancellationToken);
        await _reviewRepository.AddAsync(review, cancellationToken);
        await QaWorkflowIdempotency.CompleteAsync(
            _idempotencyStore, idempotency.Value, review.Id.Value, _clock, cancellationToken);
        
        await _auditWriter.WriteAsync(
            "QaReview", 
            review.Id.Value, 
            "Opened", 
            _currentUser.UserId!, 
            new { AnalysisRunId = request.AnalysisRunId, CandidateSnapshotHash = request.CandidateSnapshotHash }, 
            cancellationToken);

        await _unitOfWork.CommitTransactionAsync(cancellationToken);

        return review.Id.Value;
    }

    private async Task ReleaseReservationAsync(QaIdempotencyReservation reservation, CancellationToken cancellationToken)
    {
        _unitOfWork.ClearChanges();
        await QaWorkflowIdempotency.ReleaseAsync(_idempotencyStore, reservation, cancellationToken);
        await _unitOfWork.SaveChangesAsync(cancellationToken);
    }
}
